### ISSUE TITLE
Как бот запускается/устанавливается?

### ISSUE THREAD

**Issue by ProgrammingLife** [ivaaaan/vk-chat-bot#2]
Какой принцип работы у бота? Должен как демон висеть запущенным в консоли? Или как-то иным образом он должен мониторить приходящие сообщения?

**Comment by ivaaaan** [comment]
По крону.

**Comment by ProgrammingLife** [comment]
Какой рекомендуемый интервал запуска бота? Секунды 3?

**Comment by ivaaaan** [comment]
Зависит от потока сообщений. Я минуту ставил.

**Comment by ivaaaan** [comment]
Для вопросов по работе пишите мне на электронную почту. Не захламляйте issue
